#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# setup zgen
source ~/.zprezto/modules/zgen/zgen.zsh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#source ${ZDOTDIR:-$HOME}/.zprezto/modules/zgen/zgen.zsh

# set some history options
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt hist_save_no_dups
setopt hist_verify
setopt share_history
#setopt noclobber
HISTSIZE=100000
SAVEHIST=100000
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# set some more options
setopt pushd_ignore_dups
#setopt pushd_silent


# Long running processes should return time after they complete. Specified in seconds.
REPORTTIME=2
TIMEFMT="%U user %S system %P cpu %*Es total"

# Speed up autocomplete, force prefix mapping
#zstyle ':completion:*' accept-exact '*(N)'
#zstyle ':completion:*' use-cache on
#zstyle ':completion:*' cache-path ~/.zsh/cache
#zstyle -e ':completion:*:default' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)*==34=34}:${(s.:.)LS_COLORS}")';

# dedupe PATH
function dedupe_path() {
  typeset -a paths result
  paths=($path)

  while [[ ${#paths} -gt 0 ]]; do
    p="${paths[1]}"
    shift paths
    [[ -z ${paths[(r)$p]} ]] && result+="$p"
  done

  export PATH=${(j+:+)result}
}
dedupe_path

# auto suggestions plugin
#function zle-line-init() {
  #zle autosuggest-start
#}
#zle -N zle-line-init

# aliases and utility functions
[[ -s "${ZDOTDIR:-$HOME}/.zprezto/zsh_aliases" ]] && source "${ZDOTDIR:-$HOME}/.zprezto/zsh_aliases"
[[ -s "${ZDOTDIR:-$HOME}/.zprezto/zsh_functions" ]] && source "${ZDOTDIR:-$HOME}/.zprezto/zsh_functions"
[[ -s "${ZDOTDIR:-$HOME}/.zprezto/zsh_keybindings" ]] && source "${ZDOTDIR:-$HOME}/.zprezto/zsh_keybindings"
