#!/usr/bin/zsh
# taken from: https://gist.github.com/mystelynx/bca7d875f4c1596d66e0

export ZGENHOME=$HOME/.zgen
export MYZCONF=$ZGENHOME/verboze/shellconfig-master
#export ZGEN_RESET_ON_CHANGE=($HOME/.zshrc) # autoupdate on zshrc change

[[ ! -d $ZGENHOME ]] && { 
  echo "downloading zgen..."
  #git clone https://github.com/tarjoilija/zgen $ZGENHOME;
  git clone https://github.com/verboze/zgen $ZGENHOME;
}

source $ZGENHOME/zgen.zsh

funciton zgen-loadconfig() {
  echo "loading zsh plugins"

  # load zgen itself if missing
  # this could happen in a zgen uninstall -> zgen init sequence
  [[ ! -d $ZGENHOME ]] && { 
    echo "downloading zgen..."
    git clone https://github.com/tarjoilija/zgen $ZGENHOME;
  }

  # prezto options
  zgen prezto editor key-bindings 'emacs'
  zgen prezto tmux:auto-start local 'yes'
  zgen prezto prompt theme 'pure'
  zgen prezto '*:*' color 'yes'

  # prezto and plugins
  zgen prezto
  #zgen oh-my-zsh pip
  #zgen oh-my-zsh brew
  zgen prezto archive
  zgen prezto git
  zgen prezto osx
  zgen prezto gnu-utility
  zgen prezto python
  zgen prezto rsync
  zgen prezto screen
  zgen prezto tmux
  zgen prezto fasd
  zgen prezto history-substring-search
  zgen prezto syntax-highlighting

  # other zsh plugins
  zgen load TBSliver/zsh-plugin-colored-man
  zgen load mafredri/zsh-async
  #zgen load junegunn/fzf shell
  zgen load junegunn/fzf
  zgen load skx/sysadmin-util
  zgen load chrissicool/zsh-256color
  #zgen load zsh-users/zsh-completions src
  zgen load zsh-users/zsh-completions
  zgen load RobSis/zsh-completion-generator
  zgen load rimraf/k
  zgen load StackExchange/blackbox

  # highlighting and suggestions
  zgen load zsh-users/zsh-syntax-highlighting
  #zgen load tarruda/zsh-autosuggestions # really want this but conflicts with history

  # my own configs last
  zgen load verboze/shellconfig

  zgen save
}

#function zgen-uninstall() {
  #local resp
  #vared -p 'Unload all zsh plugins? All local changes will be lost (y/n): ' -c resp

  #if [[ "$resp" =~ [yY] ]]; then
    #rm -rf ${HOME}/{.zgen,.zprezto}
    #rm -rf ${HOME}/.zcompdump*
    #echo "Plugins unloaded. they will be reloaded when .zshrc is sourced next"
  #fi
#}

# load plugins if not already laoded
if ! zgen saved; then zgen-loadconfig; fi

# hook direnv if present
[[ 0 == $(which direnv >/dev/null 2>&1; echo $?) ]] && eval "$(direnv hook zsh)"

# load fishell-like completion suggestions
#function zle-line-init() { zle autosuggest-start }
#zle -N zle-line-init
